import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CartProvider } from "@/context/cartcontext";
import "./globals.css";
import ToasterComponent from "@/components/ToasterComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider>
      <ToasterComponent />
        {children}
      </CartProvider>

        </body>
    </html>
  );
}
